export const FONT_LIST = new Set([
  "sans-serif",
  "sans",
  "monospace",
  "mono",
  "cursive",
  "fantasy",
  "abadi",
  "abel regular",
  "abril fatface",
  "adlam display regular",
  "agency fb",
  "al fresco",
  "alasassy caps",
  "aldhabi",
  "alef regular",
  "aleo regular",
  "algerian",
  "amasis mt pro black",
  "amasis mt pro regular",
  "amatic sc regular",
  "angsana new",
  "angsanaupc",
  "anton regular",
  "aparajita",
  "aptos",
  "aptos black",
  "aptos display",
  "aptos mono",
  "aptos narrow",
  "aptos serif",
  "arabic typesetting",
  "aref ruqaa regular",
  "arial",
  "arial black",
  "arial narrow",
  "arial nova",
  "arial nova cond",
  "assistant regular",
  "athiti regular",
  "avenir next lt pro",
  "avenir next lt pro demi",
  "baguet script regular",
  "bahnschrift condensed",
  "bahnschrift regular",
  "bahnschrift semicondensed",
  "barlow black",
  "barlow condensed black",
  "barlow condensed regular",
  "barlow regular",
  "barlow semi condensed black",
  "barlow semi condensed regular",
  "baskerville old face",
  "batang",
  "batangche",
  "bauhaus 93",
  "bebas neue regular",
  "bell mt",
  "bembo",
  "berlin sans fb",
  "bernard mt condensed",
  "bierstadt display regular",
  "bierstadt regular",
  "bierstadtalt",
  "bierstadtalt2 cond",
  "bierstadtalt3 cond",
  "bierstadtalt4 cond",
  "bierstadtalt5 regular",
  "biome",
  "blackadder itc",
  "bodoni mt",
  "bodoni mt black",
  "bodoni mt condensed",
  "bodoni mt poster compressed",
  "book antiqua",
  "bookman old style",
  "bookshelf symbol 7",
  "boucherie block",
  "boucherie sans",
  "bradley hand itc",
  "broadway",
  "browallia new",
  "browalliaupc",
  "buxton sketch",
  "calibri",
  "californian fb",
  "calisto mt",
  "cambria",
  "cambria math",
  "candara",
  "castellar",
  "caveat brush",
  "cavolini",
  "centaur",
  "century",
  "century gothic",
  "century schoolbook",
  "chamberi super display regular",
  "charmonman regular",
  "chilgok gwon anja regular",
  "chilgok kim yeongbun regular",
  "chilgok lee jonghui regular",
  "chilgok lee wonsun regular",
  "chiller",
  "chonburi",
  "cochocib script latin pro",
  "colonna mt",
  "comic sans ms",
  "concert one",
  "congenial black",
  "congenial regular",
  "consolas",
  "constantia",
  "convection",
  "convection condensed",
  "convection symbol",
  "convection ui",
  "cooper black",
  "corbel",
  "cordia new",
  "cordiaupc",
  "courier new",
  "curlz mt",
  "dante",
  "daunpenh",
  "david",
  "daytona",
  "daytona condensed",
  "dengxian regular",
  "didact gothic regular",
  "dilleniaupc",
  "dm mono regular",
  "dm sans regular",
  "dm serif display regular",
  "dm serif text regular",
  "dokchampa",
  "dosis regular",
  "dotum",
  "dotumche",
  "dreaming outloud pro regular",
  "dreaming outloud script pro regular",
  "dubai regular",
  "eb garamond regular",
  "ebrima",
  "edwardian script itc",
  "elephant",
  "elephant pro regular",
  "engravers mt",
  "eras demi itc",
  "eucrosiaupc",
  "euphemia",
  "fahkwang regular",
  "fairwater script regular",
  "fangsong",
  "felix titling",
  "fira code regular",
  "fira code retina",
  "fira mono regular",
  "fira sans black",
  "fira sans condensed black",
  "fira sans condensed regular",
  "fira sans extra condensed black",
  "fira sans extra condensed regular",
  "fira sans regular",
  "fjalla one",
  "forte",
  "forte forward",
  "frank ruhl libre black",
  "frank ruhl libre regular",
  "franklin gothic book",
  "franklin gothic demi",
  "franklin gothic demi cond",
  "franklin gothic heavy",
  "frankruehl",
  "fredoka one",
  "freesiaupc",
  "freestyle script",
  "french script mt",
  "gabriela regular",
  "gabriola",
  "gadugi",
  "gaegu regular",
  "garamond",
  "gautami",
  "georgia",
  "georgia pro",
  "georgia pro black",
  "georgia pro cond",
  "georgia pro cond black",
  "gigi",
  "gill sans mt",
  "gill sans mt condensed",
  "gill sans nova",
  "gill sans nova cond",
  "gill sans nova cond lt",
  "gill sans nova cond xbd",
  "gisha",
  "gloucester mt extra condensed",
  "goudy old style",
  "goudy stout",
  "goudy type",
  "grandview display",
  "grandview regular",
  "grotesque",
  "gulim",
  "gulimche",
  "gungsuh",
  "gungsuhche",
  "hadassah friedlaender",
  "haettenschweiler",
  "hammersmith one regular",
  "harrington",
  "heebo black",
  "heebo regular",
  "hggothice",
  "hgmarugothicmpro",
  "hgminchoe",
  "hgpgothice",
  "hgpminchoe",
  "hgpsoeikakugothicub",
  "hgsgothice",
  "hgsminchoe",
  "hgsoeikakugothicub",
  "hgssoeikakugothicub",
  "high tower text",
  "hind colombo",
  "hind guntur regular",
  "hind jalandhar",
  "hind kochi",
  "hind madurai regular",
  "hind mysuru",
  "hind regular",
  "hind siliguri regular",
  "hind vadodara regular",
  "ibm plex mono",
  "ibm plex sans",
  "ibm plex sans condensed",
  "ibm plex serif",
  "impact",
  "imprint mt shadow",
  "inconsolata black",
  "inconsolata condensed",
  "inconsolata condensed black",
  "inconsolata expanded",
  "inconsolata expanded black",
  "inconsolata extracondensed",
  "inconsolata extraexpanded",
  "inconsolata extraexpanded black",
  "inconsolata regular",
  "inconsolata semicondensed",
  "inconsolata semicondensed black",
  "inconsolata semiexpanded",
  "inconsolata semiexpanded black",
  "inconsolata ultracondensed",
  "inconsolata ultraexpanded",
  "inconsolata ultraexpanded black",
  "ink free",
  "inter",
  "irisupc",
  "iskoola pota",
  "italianno regular",
  "jasmineupc",
  "javanese text",
  "jokerman",
  "josefin sans regular",
  "josefin slab regular",
  "juice itc",
  "jumble",
  "kaiti",
  "kalinga",
  "karla regular",
  "karla tamil inclined",
  "karla tamil upright",
  "kartika",
  "kermit",
  "kermit condensed",
  "kermit expanded",
  "khmer ui",
  "kigelia arabic regular",
  "kigelia regular",
  "klee one regular",
  "kodchiangupc",
  "kokila",
  "kristen itc",
  "krub regular",
  "kunstler script",
  "lalezar regular",
  "lao ui",
  "latha",
  "lato",
  "lato black",
  "lato regular",
  "leelawadee",
  "leelawadee ui",
  "levenim mt",
  "libre barcode 128 regular",
  "libre barcode 128 text regular",
  "libre barcode 39 extended regular",
  "libre barcode 39 extended text regular",
  "libre barcode 39 regular",
  "libre barcode 39 text regular",
  "libre barcode ean13 text regular",
  "libre baskerville",
  "libre franklin black",
  "libre franklin regular",
  "ligconsolata regular",
  "lilyupc",
  "livvic black",
  "livvic regular",
  "lobster regular",
  "lobster two",
  "lora regular",
  "lucida bright",
  "lucida fax regular",
  "lucida sans regular",
  "lucida sans typewriter oblique",
  "lucida sans typewriter regular",
  "lucida sans unicode",
  "maiandra gd",
  "malgun gothic",
  "mangal",
  "mangal pro regular",
  "marlett",
  "matura mt script capitals",
  "meddon",
  "meiryo",
  "meiryo ui",
  "merriweather black",
  "merriweather regular",
  "merriweather sans regular",
  "microsoft gothicneo",
  "microsoft himalaya",
  "microsoft jhenghei",
  "microsoft jhenghei ui",
  "microsoft new tai lue",
  "microsoft phagspa",
  "microsoft sans serif",
  "microsoft tai le",
  "microsoft uighur",
  "microsoft yahei",
  "microsoft yahei ui",
  "microsoft yi baiti",
  "mingliu",
  "mingliu_hkscs",
  "mingliu_hkscs-extb",
  "mingliu-extb",
  "miriam",
  "miriam fixed",
  "miriam libre regular",
  "mistral",
  "mitr regular",
  "modern love",
  "modern love caps",
  "modern love grunge",
  "modern no. 20",
  "mongolian baiti",
  "monotype corsiva",
  "montserrat",
  "montserrat black",
  "montserrat regular",
  "moolboran",
  "mr gabe regular",
  "ms gothic",
  "ms mincho",
  "ms outlook",
  "ms pgothic",
  "ms pmincho",
  "ms reference sans serif",
  "ms ui gothic",
  "mt extra",
  "mv boli",
  "myanmar text",
  "mystical woods rough script",
  "mystical woods smooth script",
  "nanum brush script",
  "nanum pen regular",
  "nanumgothic",
  "nanumgothiccoding",
  "nanummyeongjo",
  "narkisim",
  "neue haas grotesk text pro",
  "news gothic mt",
  "niagara engraved",
  "niagara solid",
  "nina",
  "nirmala text",
  "nirmala ui",
  "nordique inline regular",
  "noto music regular",
  "noto nastaliq urdu regular",
  "noto sans",
  "noto sans anatolian hieroglyphs regular",
  "noto sans avestan regular",
  "noto sans bassa vah regular",
  "noto sans batak regular",
  "noto sans bhaiksuki regular",
  "noto sans brahmi regular",
  "noto sans buginese regular",
  "noto sans buhid regular",
  "noto sans carian regular",
  "noto sans caucasian albanian regular",
  "noto sans chakma regular",
  "noto sans coptic regular",
  "noto sans cuneiform regular",
  "noto sans cypriot regular",
  "noto sans deseret regular",
  "noto sans devanagari black",
  "noto sans devanagari regular",
  "noto sans devanagari ui black",
  "noto sans devanagari ui regular",
  "noto sans duployan regular",
  "noto sans egyptian hieroglyphs regular",
  "noto sans elbasan regular",
  "noto sans elymaic regular",
  "noto sans glagolitic regular",
  "noto sans gothic regular",
  "noto sans grantha regular",
  "noto sans gujarati black",
  "noto sans gujarati regular",
  "noto sans gujarati ui black",
  "noto sans gujarati ui regular",
  "noto sans gunjala gondi regular",
  "noto sans hanunoo regular",
  "noto sans hatran regular",
  "noto sans imperial aramaic regular",
  "noto sans indic siyaq numbers regular",
  "noto sans inscriptional pahlavi regular",
  "noto sans inscriptional parthian regular",
  "noto sans javanese regular",
  "noto sans kaithi regular",
  "noto sans kharoshthi regular",
  "noto sans khojki regular",
  "noto sans khudawadi regular",
  "noto sans lepcha regular",
  "noto sans limbu regular",
  "noto sans linear a regular",
  "noto sans linear b regular",
  "noto sans lycian regular",
  "noto sans lydian regular",
  "noto sans mahajani regular",
  "noto sans mandaic regular",
  "noto sans manichaean regular",
  "noto sans marchen regular",
  "noto sans masaram gondi regular",
  "noto sans math regular",
  "noto sans mayan numerals regular",
  "noto sans mende kikakui regular",
  "noto sans meroitic regular",
  "noto sans miao regular",
  "noto sans modi regular",
  "noto sans mongolian regular",
  "noto sans mro regular",
  "noto sans multani regular",
  "noto sans myanmar black",
  "noto sans myanmar regular",
  "noto sans myanmar ui black",
  "noto sans myanmar ui regular",
  "noto sans nabataean regular",
  "noto sans new tai lue regular",
  "noto sans newa regular",
  "noto sans nko regular",
  "noto sans nushu regular",
  "noto sans ogham regular",
  "noto sans old hungarian regular",
  "noto sans old north arabian regular",
  "noto sans old permic regular",
  "noto sans old persian regular",
  "noto sans old sogdian regular",
  "noto sans old south arabian regular",
  "noto sans old turkic regular",
  "noto sans oriya black",
  "noto sans oriya regular",
  "noto sans oriya ui black",
  "noto sans oriya ui regular",
  "noto sans osage regular",
  "noto sans osmanya regular",
  "noto sans pahawh hmong regular",
  "noto sans palmyrene regular",
  "noto sans pau cin hau regular",
  "noto sans phagspa regular",
  "noto sans phoenician regular",
  "noto sans psalter pahlavi regular",
  "noto sans rejang regular",
  "noto sans runic regular",
  "noto sans samaritan regular",
  "noto sans saurashtra regular",
  "noto sans sharada regular",
  "noto sans shavian regular",
  "noto sans siddham regular",
  "noto sans sogdian regular",
  "noto sans soyombo regular",
  "noto sans syloti nagri regular",
  "noto sans symbols2 regular",
  "noto sans syriac black",
  "noto sans syriac regular",
  "noto sans tagalog regular",
  "noto sans tagbanwa regular",
  "noto sans tai le regular",
  "noto sans tai viet regular",
  "noto sans takri regular",
  "noto sans tamil supplement regular",
  "noto sans thai looped black",
  "noto sans thai looped regular",
  "noto sans tifinagh regular",
  "noto sans tirhuta regular",
  "noto sans ugaritic regular",
  "noto sans vai regular",
  "noto sans wancho regular",
  "noto sans warang citi regular",
  "noto sans yi regular",
  "noto sans zanabazar square regular",
  "noto serif",
  "noto serif ahom regular",
  "noto serif balinese regular",
  "noto serif dogra regular",
  "noto serif grantha regular",
  "noto serif myanmar black",
  "noto serif myanmar regular",
  "noto serif tangut regular",
  "noto traditional nushu regular",
  "nsimsun",
  "nunito black",
  "nunito regular",
  "nunito sans black",
  "nunito sans regular",
  "nyala",
  "ocrb",
  "old english text mt",
  "onyx",
  "open sans",
  "open sans regular",
  "oranienbaum",
  "oswald",
  "oswald regular",
  "oxygen mono",
  "oxygen regular",
  "pacifico regular",
  "palace script mt",
  "palanquin regular",
  "palatino linotype",
  "papyrus",
  "parchment",
  "patrick hand",
  "patrick hand sc regular",
  "perpetua",
  "petit formal script",
  "plantagenet cherokee",
  "playbill",
  "playfair display black",
  "playfair display regular",
  "playfair display sc black",
  "playfair display sc regular",
  "pmingliu",
  "pmingliu-extb",
  "poiret one regular",
  "poor richard",
  "poppins",
  "poppins black",
  "poppins regular",
  "posterama",
  "pridi regular",
  "pristina",
  "prompt black",
  "prompt regular",
  "pt mono",
  "pt sans",
  "pt sans caption",
  "pt sans narrow",
  "pt serif",
  "pt serif caption",
  "quattrocento",
  "quattrocento sans",
  "questrial regular",
  "quire sans",
  "raavi",
  "raleway",
  "raleway black",
  "raleway regular",
  "rastanty cortez",
  "ravie",
  "reem kufi regular",
  "roboto",
  "roboto",
  "roboto black",
  "roboto condensed",
  "roboto condensed",
  "roboto mono regular",
  "roboto serif 20pt",
  "roboto serif 20pt black",
  "roboto slab black",
  "roboto slab regular",
  "rockwell",
  "rockwell condensed",
  "rockwell nova",
  "rockwell nova cond",
  "rod",
  "sabon next lt",
  "sacramento",
  "sagona book",
  "sagona regular",
  "sakkal majalla",
  "sans serif collection",
  "sanskrit text",
  "seaford display regular",
  "seaford regular",
  "secular one regular",
  "segoe marker",
  "segoe print",
  "segoe pro",
  "segoe pro black",
  "segoe pro cond",
  "segoe pro display",
  "segoe sans display",
  "segoe sans display black",
  "segoe sans display hairline",
  "segoe sans small",
  "segoe sans small black",
  "segoe sans small hairline",
  "segoe sans text",
  "segoe sans text black",
  "segoe sans text hairline",
  "segoe script",
  "segoe serif banner",
  "segoe serif display",
  "segoe serif text",
  "segoe ui",
  "segoe ui black",
  "segoe ui emoji",
  "segoe ui emoji l",
  "segoe ui historic",
  "segoe ui symbol",
  "segoe ui variable display",
  "segoe ui variable small",
  "segoe ui variable text",
  "segoe xbox symbol",
  "selawik",
  "shonar bangla",
  "showcard gothic",
  "shruti",
  "simhei",
  "simplified arabic",
  "simplified arabic fixed",
  "simsun",
  "simsun-extb",
  "sitka banner",
  "sitka display",
  "sitka heading",
  "sitka small",
  "sitka subheading",
  "sitka text",
  "skeena display regular",
  "skeena regular",
  "slabo 27px",
  "snap itc",
  "source code pro",
  "source code pro black",
  "source sans pro black",
  "source sans pro regular",
  "source serif pro",
  "source serif pro black",
  "speak pro",
  "staatliches regular",
  "stcaiyun",
  "stencil",
  "stfangsong",
  "sthupo",
  "stkaiti",
  "stxihei",
  "stxingkai",
  "stxinwei",
  "stzhongsong",
  "suez one regular",
  "sylfaen",
  "symbol",
  "tahoma",
  "tempus sans itc",
  "tenorite display regular",
  "tenorite regular",
  "th sarabunpsk",
  "the hand",
  "the hand black",
  "the hand extrablack",
  "the serif hand",
  "the serif hand black",
  "the serif hand extrablack",
  "times new roman",
  "tisa offc serif pro",
  "titillium web black",
  "titillium web regular",
  "trade gothic inline regular",
  "trade gothic next",
  "trade gothic next cond",
  "trade gothic next heavy",
  "trade gothic next hvycd",
  "trade gothic next rounded",
  "traditional arabic",
  "trebuchet ms",
  "trirong black",
  "trirong regular",
  "tunga",
  "tw cen mt",
  "tw cen mt condensed",
  "ubuntu condensed",
  "ubuntu mono",
  "ubuntu regular",
  "ud digi kyokasho n-b",
  "ud digi kyokasho n-r",
  "ud digi kyokasho nk-b",
  "ud digi kyokasho nk-r",
  "ud digi kyokasho np-b",
  "ud digi kyokasho np-r",
  "univers",
  "univers condensed",
  "urdu typesetting",
  "utsaah",
  "vani",
  "varela round regular",
  "verdana",
  "verdana pro",
  "verdana pro black",
  "verdana pro cond",
  "verdana pro cond black",
  "vijaya",
  "viner hand itc",
  "vladimir script",
  "vrinda",
  "walbaum display",
  "walbaum display heavy",
  "walbaum heading",
  "walbaum text",
  "wandohope regular",
  "webdings",
  "wide latin",
  "wingdings",
  "wingdings 2",
  "wingdings 3",
  "work sans black",
  "work sans regular",
  "yesteryear",
  "yu gothic regular",
  "yu gothic ui regular",
  "yu mincho regular",
]);
